"""model_file_0.0.1

Revision ID: 4084a5e3ac05
Revises: 
Create Date: 2023-07-01 20:02:16.983125

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4084a5e3ac05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('outrecord')
    op.drop_table('customer')
    op.drop_table('order')
    op.drop_table('manager')
    op.drop_table('inrecord')
    op.drop_table('order_detail')
    op.drop_table('inventory')
    op.drop_table('category')
    op.drop_table('supplier')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('supplier',
    sa.Column('sid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sname', mysql.TEXT(), nullable=False),
    sa.Column('cname', mysql.TEXT(), nullable=False),
    sa.Column('cjob', mysql.TEXT(), nullable=False),
    sa.Column('phone', mysql.TEXT(), nullable=False),
    sa.Column('email', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('sid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('category',
    sa.Column('category', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.Column('mark', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('category'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('inventory',
    sa.Column('pid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('pid', 'sid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('order_detail',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('pid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('book_time', mysql.DATETIME(), nullable=True),
    sa.Column('order_time', mysql.DATETIME(), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('money', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('method', mysql.TEXT(), nullable=True),
    sa.Column('pay_time', mysql.DATETIME(), nullable=True),
    sa.Column('address', mysql.TEXT(), nullable=True),
    sa.Column('person', mysql.TEXT(), nullable=True),
    sa.Column('state', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('inrecord',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('category', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('pid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('in_time', mysql.DATETIME(), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=11, scale=2), nullable=True),
    sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('money', mysql.DECIMAL(precision=11, scale=2), nullable=True),
    sa.Column('person', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('manager',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.TEXT(), nullable=False),
    sa.Column('password', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('order',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('pid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('money', mysql.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('book_time', mysql.DATETIME(), nullable=True),
    sa.Column('order_time', mysql.DATETIME(), nullable=True),
    sa.Column('remark', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('customer',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.TEXT(), nullable=True),
    sa.Column('address', mysql.TEXT(), nullable=True),
    sa.Column('phone', mysql.TEXT(), nullable=True),
    sa.Column('email', mysql.TEXT(), nullable=True),
    sa.Column('remark', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('outrecord',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('category', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('pid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('sid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('out_time', mysql.DATETIME(), nullable=True),
    sa.Column('price', mysql.DECIMAL(precision=11, scale=2), nullable=True),
    sa.Column('amount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('money', mysql.DECIMAL(precision=11, scale=2), nullable=True),
    sa.Column('person', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('product',
    sa.Column('pid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('name', mysql.TEXT(), nullable=False),
    sa.Column('type', mysql.TEXT(), nullable=False),
    sa.Column('unit', mysql.TEXT(), nullable=False),
    sa.Column('sid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('category', mysql.TEXT(), nullable=False),
    sa.PrimaryKeyConstraint('pid'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
