"""empty message

Revision ID: fe72d8804522
Revises: acab45d526db
Create Date: 2023-07-02 14:44:27.837608

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fe72d8804522'
down_revision = 'acab45d526db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account', sa.String(length=18), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('manager', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', mysql.VARCHAR(length=18), nullable=False))
        batch_op.drop_column('account')

    # ### end Alembic commands ###
